//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal_v0._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informe
    {
        public int CodInforme { get; set; }
        public string Tipo { get; set; }
        public byte[] Archivo { get; set; }
        public Nullable<System.DateTime> FechaDeSubida { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> CodUsuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
